### ISSUE TITLE
LLM Vision doesn’t create Events after update to 1.7.1

### ISSUE THREAD

**Issue by fabi9276** [valentinfrlch/ha-llmvision#716]
### Checklist

- [x] I'm running the newest version of LLM Vision <https://github.com/valentinfrlch/ha-llmvision/releases/latest>
- [x] I have enabled debug logging for the integration.
- [x] I have filled out the issue template to the best of my ability.
- [x] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [x] This is a bug and not a feature request.
- [x] I have searched [open issues](https://github.com/valentinfrlch/ha-llmvision/issues) for my problem.

### Describe the issue

After I updated the LLM Vision Integration to V1.7.1, it stopped creating Events in the Calender. Also, the LLM Vision Timeline Card stopped working. The automations itself do work, i still get the phone notifications. But on the dashboard in the LLM Vision timeline Card, there’s nothing.

### Reproduction steps

1. i updatet HA to the newest version (2026.8.1)
2. i updatet the LLM Vision integration to the newest Version (1.7.1)
3. scince then, the problem occurs

I tried to reinstall the older version of LLM Vision, but it didn’t work because the newest HA Version doesn’t seem to work with the older LLM Vision Version.

### Debug logs

```text
AttributeError: 'BoschSensor' object has no attribute '__attr_state_class'. Did you mean: '_attr_state_class'?
2026-08-18 12:50:10.942 WARNING (MainThread) [bosch_thermostat_client.sensors.sensor] Can't update data for Hotwater temp. Trying uri: /system/sensors/temperatures/hotWater_t2. Error message: URI /system/sensors/temperatures/hotWater_t2 doesn not exist: 404, message='Not Found', url='http://192.168.178.38/system/sensors/temperatures/hotWater_t2'
2026-08-18 12:50:11.292 WARNING (MainThread) [bosch_thermostat_client.sensors.sensor] Can't update data for Switch temp. Trying uri: /system/sensors/temperatures/switch. Error message: URI /system/sensors/temperatures/switch doesn not exist: 404, message='Not Found', url='http://192.168.178.38/system/sensors/temperatures/switch'
2026-08-18 12:50:11.642 WARNING (MainThread) [bosch_thermostat_client.sensors.sensor] Can't update data for Chimney temp. Trying uri: /system/sensors/temperatures/chimney. Error message: URI /system/sensors/temperatures/chimney doesn not exist: 404, message='Not Found', url='http://192.168.178.38/system/sensors/temperatures/chimney'
2026-08-18 12:50:13.282 WARNING (MainThread) [bosch_thermostat_client.sensors.sensor] Can't update data for Pool temperature. Trying uri: /heatSources/poolTemperature. Error message: URI /heatSources/poolTemperature doesn not exist: 404, message='Not Found', url='http://192.168.178.38/heatSources/poolTemperature'
2026-08-18 12:50:14.609 ERROR (MainThread) [homeassistant.util.logging] Exception in async_update when dispatching 'bosch_sensor_update': ()
Traceback (most recent call last):
  File "/config/custom_components/bosch/sensor/base.py", line 118, in async_update
    if self._attr_state_class
       ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'BoschSensor' object has no attribute '__attr_state_class'. Did you mean: '_attr_state_class'?

2026-08-18 12:50:14.623 ERROR (MainThread) [homeassistant.util.logging] Exception in async_update when dispatching 'bosch_sensor_update': ()
Traceback (most recent call last):
  File "/config/custom_components/bosch/sensor/base.py", line 118, in async_update
    if self._attr_state_class
       ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'BoschSensor' object has no attribute '__attr_state_class'. Did you mean: '_attr_state_class'?

2026-08-18 12:50:27.605 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.switch_temp fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 993, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1378, in async_device_update
    await self.async_update()
  File "/config/custom_components/bosch/sensor/base.py", line 118, in async_update
    if self._attr_state_class
       ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'BoschSensor' object has no attribute '__attr_state_class'. Did you mean: '_attr_state_class'?
2026-08-18 12:50:27.607 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.chimney_temp fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 993, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1378, in async_device_update
    await self.async_update()
  File "/config/custom_components/bosch/sensor/base.py", line 118, in async_update
    if self._attr_state_class
       ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'BoschSensor' object has no attribute '__attr_state_class'. Did you mean: '_attr_state_class'?
2026-08-18 12:50:57.605 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.switch_temp fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 993, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1378, in async_device_update
    await self.async_update()
  File "/config/custom_components/bosch/sensor/base.py", line 118, in async_update
    if self._attr_state_class
       ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'BoschSensor' object has no attribute '__attr_state_class'. Did you mean: '_attr_state_class'?
2026-08-18 12:50:57.606 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.chimney_temp fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 993, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1378, in async_device_update
    await self.async_update()
  File "/config/custom_components/bosch/sensor/base.py", line 118, in async_update
    if self._attr_state_class
       ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'BoschSensor' object has no attribute '__attr_state_class'. Did you mean: '_attr_state_class'?
2026-08-18 12:51:10.942 WARNING (MainThread) [bosch_thermostat_client.sensors.sensor] Can't update data for Hotwater temp. Trying uri: /system/sensors/temperatures/hotWater_t2. Error message: URI /system/sensors/temperatures/hotWater_t2 doesn not exist: 404, message='Not Found', url='http://192.168.178.38/system/sensors/temperatures/hotWater_t2'
2026-08-18 12:51:11.292 WARNING (MainThread) [bosch_thermostat_client.sensors.sensor] Can't update data for Switch temp. Trying uri: /system/sensors/temperatures/switch. Error message: URI /system/sensors/temperatures/switch doesn not exist: 404, message='Not Found', url='http://192.168.178.38/system/sensors/temperatures/switch'
2026-08-18 12:51:11.662 WARNING (MainThread) [bosch_thermostat_client.sensors.sensor] Can't update data for Chimney temp. Trying uri: /system/sensors/temperatures/chimney. Error message: URI /system/sensors/temperatures/chimney doesn not exist: 404, message='Not Found', url='http://192.168.178.38/system/sensors/temperatures/chimney'
2026-08-18 12:51:13.292 WARNING (MainThread) [bosch_thermostat_client.sensors.sensor] Can't update data for Pool temperature. Trying uri: /heatSources/poolTemperature. Error message: URI /heatSources/poolTemperature doesn not exist: 404, message='Not Found', url='http://192.168.178.38/heatSources/poolTemperature'
2026-08-18 12:51:14.579 ERROR (MainThread) [homeassistant.util.logging] Exception in async_update when dispatching 'bosch_sensor_update': ()
Traceback (most recent call last):
  File "/config/custom_components/bosch/sensor/base.py", line 118, in async_update
    if self._attr_state_class
       ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'BoschSensor' object has no attribute '__attr_state_class'. Did you mean: '_attr_state_class'?

2026-08-18 12:51:14.593 ERROR (MainThread) [homeassistant.util.logging] Exception in async_update when dispatching 'bosch_sensor_update': ()
Traceback (most recent call last):
  File "/config/custom_components/bosch/sensor/base.py", line 118, in async_update
    if self._attr_state_class
       ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'BoschSensor' object has no attribute '__attr_state_class'. Did you mean: '_attr_state_class'?

2026-08-18 12:51:27.605 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.switch_temp fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 993, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1378, in async_device_update
    await self.async_update()
  File "/config/custom_components/bosch/sensor/base.py", line 118, in async_update
    if self._attr_state_class
       ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'BoschSensor' object has no attribute '__attr_state_class'. Did you mean: '_attr_state_class'?
2026-08-18 12:51:27.606 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.chimney_temp fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 993, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1378, in async_device_update
    await self.async_update()
  File "/config/custom_components/bosch/sensor/base.py", line 118, in async_update
    if self._attr_state_class
       ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'BoschSensor' object has no attribute '__attr_state_class'. Did you mean: '_attr_state_class'?
2026-08-18 12:51:57.606 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.switch_temp fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 993, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1378, in async_device_update
    await self.async_update()
  File "/config/custom_components/bosch/sensor/base.py", line 118, in async_update
    if self._attr_state_class
       ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'BoschSensor' object has no attribute '__attr_state_class'. Did you mean: '_attr_state_class'?
2026-08-18 12:51:57.607 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.chimney_temp fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 993, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1378, in async_device_update
    await self.async_update()
  File "/config/custom_components/bosch/sensor/base.py", line 118, in async_update
    if self._attr_state_class
       ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'BoschSensor' object has no attribute '__attr_state_class'. Did you mean: '_attr_state_class'?
2026-08-18 12:52:10.941 WARNING (MainThread) [bosch_thermostat_client.sensors.sensor] Can't update data for Hotwater temp. Trying uri: /system/sensors/temperatures/hotWater_t2. Error message: URI /system/sensors/temperatures/hotWater_t2 doesn not exist: 404, message='Not Found', url='http://192.168.178.38/system/sensors/temperatures/hotWater_t2'
2026-08-18 12:52:11.291 WARNING (MainThread) [bosch_thermostat_client.sensors.sensor] Can't update data for Switch temp. Trying uri: /system/sensors/temperatures/switch. Error message: URI /system/sensors/temperatures/switch doesn not exist: 404, message='Not Found', url='http://192.168.178.38/system/sensors/temperatures/switch'
2026-08-18 12:52:11.641 WARNING (MainThread) [bosch_thermostat_client.sensors.sensor] Can't update data for Chimney temp. Trying uri: /system/sensors/temperatures/chimney. Error message: URI /system/sensors/temperatures/chimney doesn not exist: 404, message='Not Found', url='http://192.168.178.38/system/sensors/temperatures/chimney'
2026-08-18 12:52:13.281 WARNING (MainThread) [bosch_thermostat_client.sensors.sensor] Can't update data for Pool temperature. Trying uri: /heatSources/poolTemperature. Error message: URI /heatSources/poolTemperature doesn not exist: 404, message='Not Found', url='http://192.168.178.38/heatSources/poolTemperature'
2026-08-18 12:52:14.578 ERROR (MainThread) [homeassistant.util.logging] Exception in async_update when dispatching 'bosch_sensor_update': ()
Traceback (most recent call last):
  File "/config/custom_components/bosch/sensor/base.py", line 118, in async_update
    if self._attr_state_class
       ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'BoschSensor' object has no attribute '__attr_state_class'. Did you mean: '_attr_state_class'?

2026-08-18 12:52:14.592 ERROR (MainThread) [homeassistant.util.logging] Exception in async_update when dispatching 'bosch_sensor_update': ()
Traceback (most recent call last):
  File "/config/custom_components/bosch/sensor/base.py", line 118, in async_update
    if self._attr_state_class
       ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'BoschSensor' object has no attribute '__attr_state_class'. Did you mean: '_attr_state_class'?

2026-08-18 12:52:26.853 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'camera' is undefined when rendering '{{ camera }} Snapshot'
2026-08-18 12:52:27.606 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.switch_temp fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 993, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1378, in async_device_update
    await self.async_update()
  File "/config/custom_components/bosch/sensor/base.py", line 118, in async_update
    if self._attr_state_class
       ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'BoschSensor' object has no attribute '__attr_state_class'. Did you mean: '_attr_state_class'?
2026-08-18 12:52:27.607 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.chimney_temp fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 993, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1378, in async_device_update
    await self.async_update()
  File "/config/custom_components/bosch/sensor/base.py", line 118, in async_update
    if self._attr_state_class
       ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'BoschSensor' object has no attribute '__attr_state_class'. Did you mean: '_attr_state_class'?
2026-08-18 12:52:28.582 INFO (MainThread) [custom_components.llmvision.media_handlers] Recording front_door_schnappschusse_in_hochauflosung for 2 seconds
2026-08-18 12:52:28.583 INFO (MainThread) [custom_components.llmvision.media_handlers] Fetching http://192.168.178.128:8123/api/camera_proxy/camera.front_door_schnappschusse_in_hochauflosung?token=dc903b13e52a90fb547084f11276d677dec1491d688f261afb8e29e85e58b2ea (attempt 1/2)
2026-08-18 12:52:29.384 INFO (MainThread) [custom_components.llmvision.media_handlers] Fetched camera.front_door_schnappschusse_in_hochauflosung in 0.80 seconds
2026-08-18 12:52:29.560 INFO (MainThread) [custom_components.llmvision.media_handlers] Preprocessing took: 0.18 seconds
2026-08-18 12:52:29.560 INFO (MainThread) [custom_components.llmvision.media_handlers] First iteration took: 0.98 seconds, interval adjusted to: 0.02270817756652832
2026-08-18 12:52:29.584 INFO (MainThread) [custom_components.llmvision.media_handlers] Fetching http://192.168.178.128:8123/api/camera_proxy/camera.front_door_schnappschusse_in_hochauflosung?token=dc903b13e52a90fb547084f11276d677dec1491d688f261afb8e29e85e58b2ea (attempt 1/2)
2026-08-18 12:52:30.512 INFO (MainThread) [custom_components.llmvision.media_handlers] Fetched camera.front_door_schnappschusse_in_hochauflosung in 0.93 seconds
2026-08-18 12:52:31.166 INFO (MainThread) [custom_components.llmvision.media_handlers] Preprocessing took: 0.65 seconds
2026-08-18 12:52:31.166 INFO (MainThread) [custom_components.llmvision.media_handlers] Fetching http://192.168.178.128:8123/api/camera_proxy/camera.front_door_schnappschusse_in_hochauflosung?token=dc903b13e52a90fb547084f11276d677dec1491d688f261afb8e29e85e58b2ea (attempt 1/2)
2026-08-18 12:52:31.929 INFO (MainThread) [custom_components.llmvision.media_handlers] Fetched camera.front_door_schnappschusse_in_hochauflosung in 0.76 seconds
2026-08-18 12:52:32.561 INFO (MainThread) [custom_components.llmvision.media_handlers] Preprocessing took: 0.63 seconds
2026-08-18 12:52:33.469 DEBUG (MainThread) [custom_components.llmvision.media_handlers] Saving clip to None and image to /media/llmvision/snapshots/82b668b0-front_door_schnappschusse_in_hochauflosung.jpg
2026-08-18 12:52:33.470 INFO (SyncWorker_17) [custom_components.llmvision.media_handlers] [save_clip] clip: None, image: /media/llmvision/snapshots/82b668b0-front_door_schnappschusse_in_hochauflosung.jpg
2026-08-18 12:52:33.471 DEBUG (MainThread) [custom_components.llmvision.memory] Memory([], [], 0)
2026-08-18 12:52:33.472 DEBUG (MainThread) [custom_components.llmvision.providers] Fallback provider: 01KPNER0E4XZN8GM8WG48K2W70
2026-08-18 12:52:33.472 DEBUG (MainThread) [custom_components.llmvision.providers] Provider initialized: Google(model=gemini-2.5-flash-lite, endpoint={'base_url': 'https://generativelanguage.googleapis.com/v1beta/models/{model}:generateContent?key={api_key}'})
2026-08-18 12:52:33.472 DEBUG (MainThread) [custom_components.llmvision.providers] Request data: {'contents': [{'role': 'user', 'parts': [{'text': 'Deine Aufgabe ist es, eine Reihe von Bildern zu analysieren und eine prÃ¤gnante Ereignisbeschreibung basierend auf diesen Anweisungen zu erstellen. Konzentriere dich dabei auf die Identifizierung und Beschreibung der Aktionen von Personen, Haustieren und dynamischer Objekten (z.B. Fahrzeuge) und nicht auf statische Hintergrunddetails. Wenn mehrere Bilder gegeben werden, verfolge und fasse Bewegungen oder VerÃ¤nderungen Ã¼ber die Zeit zusammen (z.B. â€œEine Person geht zur HaustÃ¼râ€, â€œEin Auto fÃ¤hrt aus der Einfahrtâ€ oder â€žJemand sitzt auf dem Stuhlâ€œ). Halte die Antworten kurz und objektiv. Vermeide Spekulationen und priorisiere beobachtbare AktivitÃ¤ten. Die Zusammenfassung muss weniger als 255 Zeichen lang sein, daher muss sie so gut wie mÃ¶glich innerhalb dieser Zeichenbegrenzung zusammengefasst werden.'}]}, {'role': 'user', 'parts': [{'text': 'front_door_schnappschusse_in_hochauflosung-frame-0:'}, {'inline_data': {'mime_type': 'image/jpeg', 'data': '<long_string>'}}, {'text': 'The attached images are frames from a live camera feed. Beschreibe kurz die beobachtete Bewegung.\n\nFokussiere dich ausschlieÃŸlich auf:\n- Menschen\n- Tiere\n\nIgnoriere statische Objekte und Umgebung.\n\nFormuliere eine klare, natÃ¼rliche Beobachtung in einem Satz.\n\nWenn keine Bewegung sichtbar ist, antworte exakt mit:\nKeine AktivitÃ¤t beobachtet'}]}], 'generationConfig': {'maxOutputTokens': 50, 'temperature': 0.5, 'topP': 0.9}}
2026-08-18 12:52:33.472 DEBUG (MainThread) [custom_components.llmvision.providers] Posting to https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-lite:generateContent
```

**Comment by airbornetrooper82573** [comment]
I recently saw an update and applied. Also no new events on my timeline card. I am on v1.7.1 too. Hasn’t had any events added since September 6th.

**Comment by TTr0n** [comment]
My llmvision event_summary blueprint works most of the time, but video analyzer not.

> 2026-09-16 13:39:39.707 DEBUG (MainThread) [custom_components.llmvision.media_handlers] Saving clip to None and image to /media/llmvision/snapshots/17033f47-2.jpg
>2026-09-16 13:40:11.311 DEBUG (MainThread) [custom_components.llmvision.timeline] Fetching events with filters - cameras: None, categories: None, labels: [], start: 2026-08-23T13:40:11.309935+02:00, end: 2026-09-16T13:40:11.309935+02:00, include_no_activity: False
>2026-09-16 13:40:11.325 INFO (MainThread) [custom_components.llmvision.timeline] [CLEANUP] Removing unlinked snapshot: 17033f47-2.jpg
>2026-09-16 13:40:11.327 DEBUG (MainThread) [custom_components.llmvision.timeline] [CLEANUP] Removed 1 orphaned snapshot(s)
