### ISSUE TITLE
Data Analyzer: add_images() missing positional argument: 'expose_images_persist'

### ISSUE THREAD

**Issue by iamjoshk** [valentinfrlch/ha-llmvision#220]
### Bug Description

**Version**: v1.3.9

### Service Call

```yaml
action: llmvision.data_analyzer
data:
  message: what number is in the blue box
  image_file: /media/llmvision/snapshot/snapshot.jpg
  image_entity:
    - camera.my_camera
  target_width: 1280
  max_tokens: 5
  temperature: 0.1
  provider: xxxxxxx
  sensor_entity: input_number.my_input_number
  include_filename: false
```
### Logs

Debug log shows no additional information.
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 816, in handle_execute_script
    script_result = await script_obj.async_run(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        msg.get("variables"), context=context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1810, in async_run
    return await asyncio.shield(create_eager_task(run.async_run()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 464, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 528, in _async_step
    self._handle_exception(
    ~~~~~~~~~~~~~~~~~~~~~~^
        ex, continue_on_error, self._log_exceptions or log_exceptions
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 558, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 526, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 764, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 727, in _async_run_long_action
    return await long_task
           ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2795, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2838, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/llmvision/__init__.py", line 457, in data_analyzer
    request = await processor.add_visual_data(image_entities=call.image_entities,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
                                              )
                                              ^
  File "/config/custom_components/llmvision/media_handlers.py", line 509, in add_visual_data
    await self.add_images(
          ~~~~~~~~~~~~~~~^
        image_entities=image_entities,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
        expose_images=False
        ^^^^^^^^^^^^^^^^^^^
    )
    ^
TypeError: MediaProcessor.add_images() missing 1 required positional argument: 'expose_images_persist'
```

**Comment by valentinfrlch** [comment]
Thanks for raising this issue. There is indeed a mistake in the code. Will be fixed in the next release.

**Comment by iamjoshk** [comment]
This is working in v1.4.0-rc1. Thank you!

**Comment by valentinfrlch** [comment]
Thanks for reporting back!
